traiterJson({
"trait":1,
"scoreJ":12,
"scoreJ5":2,
"scoreR":2,
"scoreR5":0,
"bonusJ":3,
"malusJ":3,
"bonusR":3,
"malusR":2,
"cols":[
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":1, "couleur":2},
	{"nb":5, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":2, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":2, "couleur":1},
	{"nb":4, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":4, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":4, "couleur":1},
	{"nb":3, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":3, "couleur":2},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":3, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":4, "couleur":1},
	{"nb":4, "couleur":2},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":5, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":4, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
]
});